name: Deploy to Raspberry Pi
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Raspberry Pi
        run: |
          ssh pi@176.10.254.141 'cd ~/var/www/dmelin.se/ && git pull --force origin main'